### ISSUE TITLE
Impossibile ultimare l'installazione

### ISSUE THREAD

**Issue by mmaridev** [Scuola247/PostgreSQL#1]
Arrivato al punto della guida

```
poi creiamo il database vero e proprio con:
database.sql
```

Non riesco a trovare il file database.sql e sono impossibilitato ad andare avanti. Sfugge a me qualcosa?

**Comment by folstuff** [comment]
C'erano delle imprecisioni nel file README.md che ho appena corretto mi faccia sapere se riesce a finire l'installazione del db.

**Comment by mmaridev** [comment]
Ci solo un paio di errori di battitura: `datasets/data.sl` invece di `datasets/data.sql` e `public/datas.sql` invece di `public/data.sql`
Per il resto confermo di essere riuscito a portare a termine la procedura. Un sentito ringraziamento.

**Comment by Lucaccc** [comment]
> Ci solo un paio di errori di battitura: `datasets/data.sl` invece di `datasets/data.sql` e `public/datas.sql` invece di `public/data.sql` Per il resto confermo di essere riuscito a portare a termine la procedura. Un sentito ringraziamento.

Salve, ho visto che è riuscito a completare l'installazione...potrebbe darmi una mano?
